baseURL = "http://graygzou.github.io/graygzou-personal-blog/"
languageCode = "en"
title = "Grégoire Boiron"
enableRobotsTXT=true
log=true
googleAnalytics="todo"
EnableMissingTranslationPlaceholders=true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    lang = "en"
    contentDir = "content/en"
    languageName = "English"
    weight = 1
    [languages.en.params]
      emoji = ":us:"
      linkedin = "todo"
  [languages.fr]
    lang = "fr"
    contentDir = "content/fr"
    languageName = "Français"
    weight = 2
    [languages.fr.params]
      emoji = ":fr:"
      linkedin = "todo"

[params]
  mainSections = ["posts"]
  blogSections = ["tutorials", "cheatsheets", "miscallenous", "tipsAndTricks"]
  author = "Grégoire Boiron"
  role = "Generalist Programmer"
  email = "gregoire.boiron@gmail.com"
  description = "Personal blog of the amazing Graygzou. Find tutorials, tips and tricks, and many more!"
  [params.social]
    [params.social.twitter]
      name = "Twitter"
      path = "https://twitter"
      order = 1
    [params.social.github]
      name = "Github"
      path = "https://github"
      order = 2
    [params.social.linkedin]
      name = "Linkedin"
      path = "https://linkedin"
      order = 3
    [params.social.gamejolt]
      name = "Gamejolt"
      path = "https://gamejolt"
      order = 4
    [params.social.itch]
      name = "Itch-dot-io"
      path = "https://itch.io"
      order = 5

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = ""
    weight = -110
  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = ""
    weight = -80
  [[menu.main]]
    name = "About"
    identifier = "About"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = ""
    weight = -70
  [[menu.main]]
    name = "Website"
    identifier = "Website"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "https://graygzou.github.io/"
    weight = -70

