[[main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "#"
    weight = -110

[[main]]
    identifier = "blog"
    name = "Blog"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "posts/"
    weight = -80

[[main]]
    identifier = "about"
    name = "About"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "about/"
    weight = -70

[[main]]
    identifier = "website"
    name = "Website"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "https://graygzou.github.io/"
    weight = -70