author = "Grégoire Boiron"
role = "Generalist Programmer"
birthdayYear = 1994
email = "gregoire.boiron@gmail.com"
description = "Grégoire Boiron Personal Blog"
extendedDescription = "Personal blog of the amazing Graygzou. Find tutorials, tips and tricks, and many more!"
images = ["/img/me.jpg"]
formspreeEndpoint = "https://formspree.io/xwkrekv"

nbLatestPosts = 4
nbPostSectionPreview = 3
mainSections = ["posts"]
menuIdNewPage = ["website"]
blogSections = ["tutorials", "cheatsheets", "concepts", "tipsAndTricks"]
copyrighthtml = "Copyright &#xA9; %%date%% Grégoire Boiron. All rights reserved."
participatedProjects = ["__Cuphead__: Don't Deal With The Devil", "__F1 Mobile Racing__"]

[social]
    [social.twitter]
        name = "Twitter"
        path = "https://twitter.com/GrayGzou"
        order = 1
    [social.github]
        name = "Github"
        path = "https://github.com/Graygzou"
        order = 2
    [social.linkedin]
        name = "Linkedin"
        path = "https://www.linkedin.com/in/gregoire-boiron/"
        order = 3
    [social.gamejolt]
        name = "Gamejolt"
        path = "https://gamejolt.com/@GrayGzou"
        order = 4
    [social.itch]
        name = "Itch-dot-io"
        path = "https://graygzou.itch.io/"
        order = 5

[tagsCategory]
    [tagsCategory.language]
      title = "Languages"
      color = "#78dce8"
      tags = ["csharp", "c++", "java", "lua", "js", "go", "ruby", "ada", "html", "css", "bash"]
    [tagsCategory.engines]
      title = "Engines"
      color = "#ab9df2"
      tags = ["unity", "unreal", "Jmonkey", "openGL", "webGL"]
    [tagsCategory.techs]
      title = "Tech"
      color = "#ea9c77"
      tags = ["docker", "raspberry-pi", "git", "branching", "hugo"]
    [tagsCategory.concepts]
      title = "Concepts"
      color = "#fa2c71"
      tags = ["web", "plugins"]

[shareon]
  [shareon.facebook]
    name = "Facebook"
    username = ""
  [shareon.Twitter]
    name = "Twitter"
    username = "GrayGzou"
  [shareon.Linkedin]
    name = "Linkedin"
    username = "Grégoire Boiron"